# Generated by Django 5.2.4 on 2025-07-14 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='আইডি')),
                ('nid_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='National ID Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('education', models.CharField(blank=True, choices=[('BSC', 'B.Sc in Agriculture'), ('MSC', 'M.Sc in Agriculture'), ('PHD', 'PhD inploma in Agricu Agriculture'), ('DIP', 'Dilture'), ('OTH', 'Other')], max_length=3, null=True, verbose_name='Education Qualification')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Educational Institution')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Graduation Year')),
                ('specialization', models.CharField(choices=[('CR', 'Crop Disease Management'), ('IR', 'Irrigation Technology'), ('OR', 'Organic Farming'), ('SD', 'Seed Technology'), ('PE', 'Pesticide Management'), ('CL', 'Climate Adaptation'), ('MA', 'Agricultural Machinery')], default='CR', max_length=2, verbose_name='Specialization')),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Experience (Years)')),
                ('workplace', models.CharField(help_text='District/Upazila Agriculture Office, Research Institute etc.', max_length=100, verbose_name='Workplace')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('days_available', models.CharField(choices=[('SW', 'Saturday-Wednesday'), ('ST', 'Sunday-Thursday'), ('MF', 'Monday-Friday'), ('FL', 'Flexible')], default='SW', max_length=2, verbose_name='Available Days')),
                ('time_available', models.CharField(default='9:00 AM - 4:00 PM', max_length=100, verbose_name='Available Time')),
                ('total_meetings', models.PositiveIntegerField(default=0, verbose_name='Total Meetings Conducted')),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average Rating')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='officers/profile_pictures/', verbose_name='Profile Picture')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Officer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Agriculture Officer',
                'verbose_name_plural': 'Agriculture Officers',
            },
        ),
    ]
