# Generated by Django 5.2.4 on 2025-07-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_alter_officer_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='officer',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Availabilty'),
        ),
    ]
