# Generated by Django 5.2.4 on 2025-07-15 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_remove_officer_is_verified_officer_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='officer',
            name='total_ratings',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Total Rating'),
        ),
    ]
