# Generated by Django 5.2.4 on 2025-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_remove_officer_average_rating_officer_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='specialization',
            field=models.CharField(choices=[('CR', 'ফসল রোগ ব্যবস্থাপনা'), ('IR', 'সেচ প্রযুক্তি'), ('OR', 'জৈব কৃষি'), ('SD', 'বীজ প্রযুক্তি'), ('PE', 'কীটনাশক ব্যবস্থাপনা'), ('CL', 'জলবায়ু অভিযোজন'), ('MA', 'কৃষি যন্ত্রপাতি')], default='CR', max_length=2, verbose_name='Specialization'),
        ),
    ]
