# Generated by Django 5.2.4 on 2025-07-15 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0005_alter_officer_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='days_available',
            field=models.CharField(choices=[('SW', 'শনিবার - বুধবার'), ('ST', 'রবিবার-বৃহস্পতিবার'), ('MF', 'সোমবার-শুক্রবার'), ('FL', 'Flexible')], default='SW', max_length=2, verbose_name='Available Days'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Experience (Years)'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, default=2000, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='total_ratings',
            field=models.FloatField(default=0, verbose_name='Total Rating'),
        ),
        migrations.CreateModel(
            name='OfficerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('discussion_content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinglist', to='officers.officer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officerbooking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
