# Generated by Django 5.2.4 on 2025-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0006_alter_officer_days_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerbook',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
