# Generated by Django 5.2.4 on 2025-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0007_officerbook_meeting_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerbook',
            name='is_cancel',
        ),
        migrations.AlterField(
            model_name='officerbook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='pending', max_length=150),
        ),
    ]
