# Generated by Django 5.2.4 on 2025-07-14 08:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category_image', models.ImageField(upload_to='categories')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ফসলের নাম',
                'verbose_name_plural': 'ফসলের নাম সমূহ',
            },
        ),
        migrations.CreateModel(
            name='CropVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varity_name', models.CharField(max_length=150, verbose_name='জাতের নাম')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='variety_images')),
                ('verity_type', models.CharField(choices=[('hybrid', 'হাইব্রিড'), ('high_yielding', 'উচ্চ ফলনশীল'), ('local', 'স্থানীয় জাত'), ('irri', 'আইআরআরআই জাত')], max_length=200, verbose_name='জাতের ধরন')),
                ('duration', models.CharField(max_length=150, verbose_name='সময়কাল')),
                ('yield_amount', models.CharField(help_text='টন/হেক্টরে', verbose_name='গড় ফলন')),
                ('year_released', models.CharField(verbose_name='উদ্ভাবনের বছর')),
                ('institute', models.CharField(max_length=200, verbose_name='উদ্ভাবক প্রতিষ্ঠান')),
                ('suitable_area', models.TextField(verbose_name='প্রস্তাবিত এলাকা')),
                ('grain_type', models.CharField(max_length=100, verbose_name='দানাদার ধরন')),
                ('is_popular', models.BooleanField(default=False, verbose_name='জনপ্রিয় জাত')),
                ('is_new', models.BooleanField(default=False, verbose_name='নতুন জাত')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='অতিরিক্ত তথ্য')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crop.category', verbose_name='ফসলের নাম')),
            ],
            options={
                'verbose_name': 'জাতের তথ্য',
                'verbose_name_plural': 'জাতের তথ্যসমূহ',
            },
        ),
        migrations.CreateModel(
            name='CultivationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='সম্পূর্ণ চাষ পদ্ধতি')),
                ('varity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_info', to='crop.cropvarity')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, verbose_name='রোগের নাম')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='সার সংক্ষেপ')),
                ('symptoms', models.TextField(verbose_name='রোগের লক্ষণ')),
                ('causes', models.TextField(blank=True, null=True, verbose_name='রোগের কারণ')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='প্রতিকার')),
                ('treatment', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='চিকিৎসা বা ব্যবস্থাপনা')),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/', verbose_name='রোগের ছবি')),
                ('is_major', models.BooleanField(default=False, verbose_name='প্রধান রোগ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_disease_info', to='crop.category', verbose_name='ফসলের নাম')),
            ],
            options={
                'verbose_name': 'রোগের তথ্য',
                'verbose_name_plural': 'রোগের তথ্যসমূহ',
            },
        ),
        migrations.CreateModel(
            name='DiseasePestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_diseases', models.TextField(verbose_name='প্রধান রোগ')),
                ('major_pests', models.TextField(verbose_name='প্রধান পোকা')),
                ('advice', models.TextField(blank=True, null=True, verbose_name='পরামর্শ দিন')),
                ('variety', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disease_info', to='crop.cropvarity')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='সার এর নাম')),
                ('amount_per_hectare', models.CharField(max_length=100, verbose_name='পরিমান')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='crop.cropvarity')),
            ],
        ),
    ]
