# Generated by Django 5.2.4 on 2025-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_officer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=False, max_length=150),
            preserve_default=False,
        ),
    ]
