# Generated by Django 5.2.4 on 2025-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
